old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            vhost: avia_api
    producers:
        notifications:
            connection: default
            exchange_options:
                name: emails
                type: direct
    
    consumers:
        notifications:
            connection: default
            exchange_options:
                name: emails
                type: direct
            queue_options:
                name: emails
                auto_delete: false
            callback: email_service
